import type { ITheme } from "@xterm/xterm";

/**
 * A theme is the full set of design tokens that drive the app's look. It is
 * intentionally a flat, serializable schema: every field maps to a CSS variable
 * (or the terminal palette), so a theme can be authored by hand OR generated by
 * an AI from a prompt and dropped into THEMES with no code changes.
 *
 * To add a token: add it here, set it in every theme file, write it in
 * applyTheme() (index.ts), and reference var(--…) from styles.css.
 */
export interface Theme {
  id: string;
  /** Display name shown in the Appearance picker. */
  name: string;
  /** Drives the native window chrome (traffic lights) light/dark. */
  appearance: "dark" | "light";

  colors: {
    /** App background (terminal area). */
    bg: string;
    /** Raised surfaces: sidebar, tab strip, pane headers. */
    bg2: string;
    /** Hover / active surfaces, menus, badges. */
    bg3: string;
    /** Hairline borders and dividers. */
    border: string;
    /** Primary text. */
    fg: string;
    /** Secondary / muted text and icons. */
    fgDim: string;
    /** Accent: active indicators, focus rings, the brand color. */
    accent: string;
    /** Translucent accent for selection / drop-target fills. */
    accentSoft: string;
  };

  /** Corner roundness, three steps small → large. */
  radius: {
    /** Buttons, badges, inputs, small controls. */
    sm: string;
    /** Rows, tabs, menu items. */
    md: string;
    /** Popovers, menus, cards, the settings window. */
    lg: string;
  };

  /** The xterm.js terminal palette. */
  term: ITheme;
}
