import type { ITheme } from "@xterm/xterm";

/**
 * A theme is the full set of design tokens that drive the app's look. It is
 * intentionally a flat, serializable schema: every field maps to a CSS variable
 * (or the terminal palette), so a theme can be authored by hand OR generated by
 * an AI from a prompt and dropped into THEMES with no code changes.
 *
 * To add a token: add it here, set it in every theme file, write it in
 * applyTheme() (index.ts), and reference var(--…) from styles.css.
 */
export interface Theme {
  id: string;
  /** Display name shown in the Appearance picker. */
  name: string;
  /** Drives the native window chrome (traffic lights) light/dark. */
  appearance: "dark" | "light";

  colors: {
    /** App background (terminal area). */
    bg: string;
    /** Raised surfaces: sidebar, tab strip, pane headers. */
    bg2: string;
    /** Hover / active surfaces, menus, badges. */
    bg3: string;
    /** Hairline borders and dividers. */
    border: string;
    /** Primary text. */
    fg: string;
    /** Secondary / muted text and icons. */
    fgDim: string;
    /** Accent: active indicators, focus rings, the brand color. */
    accent: string;
    /** Translucent accent for selection / drop-target fills. */
    accentSoft: string;
  };

  /** Corner roundness, three steps small → large. */
  radius: {
    /** Buttons, badges, inputs, small controls. */
    sm: string;
    /** Rows, tabs, menu items. */
    md: string;
    /** Popovers, menus, cards, the settings window. */
    lg: string;
  };

  /**
   * Sidebar chrome. Optional — omit to inherit `colors.bg2` background and a
   * `colors.border` right divider. A theme can give the sidebar its own
   * background, and set `border: "transparent"` to drop the right divider.
   */
  sidebar?: {
    bg?: string;
    border?: string;
  };

  /**
   * Other chrome surfaces. All optional, with sensible fallbacks in applyTheme.
   */
  chrome?: {
    /** Top strip (workspace header + tab bar). A color OR a gradient. Default: colors.bg2. */
    topBar?: string;
    /** Divider under the top strip; "transparent" to drop it. Default: colors.border. */
    topBarBorder?: string;
    /** Active tab background. Default: colors.bg. */
    activeTab?: string;
    /** Active sidebar row background. Default: colors.bg3. */
    activeRow?: string;
    /**
     * Gap around the floating terminal card — a CSS padding shorthand, so the
     * four sides can differ (e.g. "8px" or "0 8px 8px 8px"). Default: "8px".
     * Set "0" for a flush, edge-to-edge layout (no floating card).
     */
    paneGap?: string;
    /** Terminal card corner radius. Default: radius.lg. */
    paneRadius?: string;
    /** Terminal card border color; "transparent" to drop it. Default: colors.border. */
    paneBorder?: string;
    /** Terminal card box-shadow (full CSS value); "none" for a flat look. */
    paneShadow?: string;
  };

  /**
   * Escape hatch: raw CSS custom-property overrides applied last, so a theme
   * can restyle anything that isn't a first-class token yet (e.g. "--accent",
   * "--radius-lg", or any var referenced in styles.css). Keys may omit the
   * leading "--".
   */
  vars?: Record<string, string>;

  /** The xterm.js terminal palette. */
  term: ITheme;
}
